package:
  name: sensorutils
  version: {"1.0.1."+ environ.get('GIT_DESCRIBE_NUMBER') }

source:
  git_url: https://github.com/USGS-Astrogeology/SensorUtils.git

requirements:
  build:
    - cmake >=3.10
    - armadillo

test:
  commands:
    - test -e $PREFIX/lib/libsensorutils.so 

about:
  home: https://github.com/USGS-Astrogeology/SensorUtils
  license: None
  summary: "This is a library for sensor utilities"
